### ISSUE TITLE
Full GUI experience for Harden Windows Security Module

### ISSUE THREAD

**Issue by HotCakeX** [HotCakeX/Harden-Windows-Security#282]
The Harden Windows Security module will have full GUI experience, including all of its cmdlets and features.

- [x] Applying protection through the GUI
- [x] Performing Audit and compliance checking through the GUI
- [x] New modern tooltips for the entire GUI
- [x] Removing protection through the GUI
- [x] Modifying individual ASR rules through the GUI
- [ ] BitLocker activation and enrollment through the GUI

**Comment by HotCakeX** [comment]
Yes for sure!

**Comment by JM2K69** [comment]
If you want some help.

**Comment by HotCakeX** [comment]
> If you want some help.

Sure, appreciate that, I'll take all the help i can get :)
but first these 2 issues need to be taken care of by the .NET and WPF teams
https://github.com/dotnet/wpf/discussions/8533
https://github.com/dotnet/core/issues/9338

They will allow me to use modern theming in WPF and PowerShell 7.5 which is based on .NET 9.

**Comment by JM2K69** [comment]
There is also another library mahapps https://github.com/MahApps/MahApps.Metro but this add dependency ? As you want.

**Comment by HotCakeX** [comment]
> There is also another library mahapps https://github.com/MahApps/MahApps.Metro but this add dependency ? As you want.

I don't want to add 3rd party dependencies/DLLs to the module [wpf.ui](https://github.com/lepoco/wpfui) integration with .NET 9 will provide everything we need.

**Comment by JM2K69** [comment]
Ok

**Comment by HotCakeX** [comment]
Adding this discussion post about required GUI changes:
https://github.com/HotCakeX/Harden-Windows-Security/discussions/286
